name: Build and Release Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.4  # Replace with the desired Python version (e.g., 3.9)

    - name: Install dependencies
      run: |
        pip install cython pyinstaller PyQt5 Pillow

    - name: Build executable
      run: |
        python setup.py build_ext --inplace
        pyinstaller --onefile --noconsole --name image-optimizer main2.pyx
        pyinstaller image-optimizer.spec  # Replace with the appropriate command or file name

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Executable
        path: dist/  # Replace with the directory where your executable is generated

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: v1.0.0  # Replace with the desired tag name
        release_name: Release 1.0.0  # Replace with the desired release name
        body: |
          Release notes and description for the release.
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/image-optimizer.exe  # Replace with the path to your executable file
        asset_name: image-optimizer.exe  # Replace with the desired name for the asset
        asset_content_type: application/octet-stream
